---
title: "README"
author: "Xavier Vollenweider"
date: "14 February 2020"
output: md_document
---
# FDFA_01
The lack of coherent and comparable data on migration restricts our ability to design appropriate migration and development policies, protect and assist migrant populations, and monitor progress towards the achievement of migration-relevant targets in the Sustainable Development Goals (SDGs). This is particularly true for migration movements across the Global South, international migration movements at the subnational-unit level (i.e. between spatial units located in different countries), and migration data disaggregated by basic characteristic such as sex.

This project aims to address this challenge by providing a new globally consistent and harmonized dataset of sex-disaggregated migration movements estimates at the subnational level within and between all low- and middle-income countries. 

The new dataset is available at this link: ftp://ftp.worldpop.org.uk/tmp/FDFA_Subnational_MigrationEstimates/

This repository hosts the code of the dashboard providing interactive mapping and visualization of this new dataset. It is deployed <a href="https://gravier.shinyapps.io/fdfa_01_dev_v4/" target="_blank">here</a>.


The dataset has been developped by Alessandro Sorichetta (PI)^1^, Andrew J. Tatem (PI)^1^ ^3^, Silvia Ceausu^1^, Dorothea Woods^1^ ^2^, Chigozie E. Utazi^1^ and Guy Abel^4^. The dashboard has been developped by Xavier Vollenweider^3^ with help from Visvanathan Subramaniam^3^.
<br>
<br>
<br>
^1^ WorldPop, University of Southampton, UK.<br>
^2^ GeoData, University of Southampton, UK. <br>
^3^ Flowminder Foundation, Switzerland. <br>
^4^ ADRI, Shanghai University, China. <br>