---
title: "Chord"
author: "Xavier Vollenweider"
date: "03 February 2020"
output: md_document

---
## Chord

***
This Chord diagram is another representation of migration movements between countries or administrative units.

*"A chord diagram represents flows or connections between several entities. Each entity is represented by a fragment on the outer part of the circular layout. Then, arcs are drawn between each entities. The size of the arc is proportional to the importance of the flow." (<a href="https://www.data-to-viz.com/graph/chord.html" target="_blank">From Data to Viz</a>)* 



Larger is the arc, larger is the migration movement from one entitiy to the next. Two filters are applied to the data:

*   The dropdown menu `Number of relations` allows the user to filter the maximum number of relations per entity (rnked by order of importance)
*   The slider widget `Maximum number of relations` determine the number of relations to draw out of these pre-selected relations.


###Data sources and methods
The migration **estimates** for *international* and *internal* movements come from two different models and data sources: 

*	  `International`: ADRI database (UNDESA): Iterative Proportional Fitting to disaggregate national estimates to subnational level
*	  `Internal`: IMPUMSI database (censuses, 40 countries): statistical model fed by Remote sensed and other geographic data to out-predict internal migration in countries where census data on migration is not available

These migration figures are **estimates** of international and internal migration of 2010. These figures are not meant to represent the actual count of migrants. See the section *Background & methods* for more information available by clicking on the button on top left pan.
